name: aqua
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - brotli=1.1.0=h2466b09_3
  - brotli-bin=1.1.0=h2466b09_3
  - bzip2=1.0.8=h2466b09_7
  - ca-certificates=2025.6.15=h4c7d964_0
  - cairo=1.18.4=h5782bbf_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.2=py313h1ec8472_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - double-conversion=3.3.1=he0c23c2_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.58.4=py313hb4c8b1a_0
  - freetype=2.13.3=h57928b3_1
  - graphite2=1.3.14=he0c23c2_0
  - harfbuzz=11.2.1=h8796e6f_0
  - icu=75.1=he0c23c2_0
  - iniconfig=2.0.0=pyhd8ed1ab_1
  - intel-openmp=2024.2.1=h57928b3_1083
  - kiwisolver=1.4.7=py313h1ec8472_0
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h6470a55_1
  - libblas=3.9.0=32_h641d27c_mkl
  - libbrotlicommon=1.1.0=h2466b09_3
  - libbrotlidec=1.1.0=h2466b09_3
  - libbrotlienc=1.1.0=h2466b09_3
  - libcblas=3.9.0=32_h5e41251_mkl
  - libclang13=20.1.7=default_h6e92b77_0
  - libdeflate=1.24=h76ddb4d_0
  - libexpat=2.7.0=he0c23c2_0
  - libffi=3.4.6=h537db12_1
  - libfreetype=2.13.3=h57928b3_1
  - libfreetype6=2.13.3=h0b5ce68_1
  - libgcc=15.1.0=h1383e82_3
  - libglib=2.84.2=hbc94333_0
  - libgomp=15.1.0=h1383e82_3
  - libhwloc=2.11.2=default_ha69328c_1001
  - libiconv=1.18=h135ad9c_1
  - libintl=0.22.5=h5728263_3
  - libjpeg-turbo=3.1.0=h2466b09_0
  - liblapack=3.9.0=32_h1aa476e_mkl
  - liblzma=5.8.1=h2466b09_2
  - libmpdec=4.0.0=h2466b09_0
  - libpng=1.6.49=h7a4582a_0
  - libsqlite=3.50.1=hf5d6505_6
  - libtiff=4.7.0=h05922d8_5
  - libwebp-base=1.5.0=h3b0e114_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_9
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.13.8=h442d1da_0
  - libxslt=1.1.39=h3df6e99_0
  - libzlib=1.3.1=h2466b09_2
  - line_profiler=4.2.0=py313h1ec8472_0
  - matplotlib=3.10.3=py313hfa70ccb_0
  - matplotlib-base=3.10.3=py313h81b4f16_0
  - mkl=2024.2.2=h66d3029_15
  - munkres=1.1.4=pyhd8ed1ab_1
  - mypy=1.16.1=py313ha7868ed_0
  - mypy_extensions=1.1.0=pyha770c72_0
  - numpy=2.3.0=py313hefb8edb_0
  - openjpeg=2.5.3=h4d64b90_0
  - openssl=3.5.0=ha4e3fda_1
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.0=py313hf91d08e_0
  - pathspec=0.12.1=pyhd8ed1ab_1
  - patsy=1.0.1=pyhd8ed1ab_1
  - pcre2=10.45=h99c9b8b_0
  - pillow=11.2.1=py313hda88b71_0
  - pip=25.1.1=pyh145f28c_0
  - pixman=0.46.2=had0cd8c_0
  - pluggy=1.6.0=pyhd8ed1ab_0
  - psutil=7.0.0=py313ha7868ed_0
  - pthread-stubs=0.4=h0e40799_1002
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.2.3=pyhd8ed1ab_1
  - pyside6=6.9.1=py313hd8d090c_0
  - pytest=8.4.1=pyhd8ed1ab_0
  - python=3.13.5=h7de537c_102_cp313
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.13=7_cp313
  - pytz=2025.2=pyhd8ed1ab_0
  - qhull=2020.2=hc790b64_5
  - qt6-main=6.9.1=h02ddd7d_0
  - scipy=1.15.2=py313h2eca4b9_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - six=1.17.0=pyhd8ed1ab_0
  - snakeviz=2.2.2=pyhd8ed1ab_1
  - statsmodels=0.14.4=py313h8e081ca_0
  - tbb=2021.13.0=h62715c5_1
  - tk=8.6.13=h2c6b04d_2
  - tomli=2.2.1=pyhd8ed1ab_1
  - tornado=6.5.1=py313ha7868ed_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - typing_extensions=4.14.0=pyhe01879c_0
  - tzdata=2025b=h78e105d_0
  - ucrt=10.0.22621.0=h57928b3_1
  - vc=14.3=h41ae7f8_26
  - vc14_runtime=14.44.35208=h818238b_26
  - xorg-libxau=1.0.12=h0e40799_0
  - xorg-libxdmcp=1.1.5=h0e40799_0
  - zstd=1.5.7=hbeecb71_2
prefix: C:\Users\liamm\anaconda3\envs\aqua
